ecolos_glossary_plugin_admin:
  resource: "@EcolosSyliusGlossaryPlugin/Resources/config/routing/admin.yaml"
  prefix: /admin

ecolos_glossary_plugin_shop:
  resource: "@EcolosSyliusGlossaryPlugin/Resources/config/routing/shop.yaml"
  prefix: /{_locale}



